#!/bin/bash
# Manual NAS Server Deployment Instructions
# CBH BCP Emergency Access System

echo "🔒 CBH BCP NAS Server - Manual Deployment Guide"
echo "================================================"
echo ""
echo "Since automated SSH deployment had issues, here's how to manually deploy:"
echo ""

echo "📋 STEP 1: Prepare Files"
echo "========================"
echo "Current directory: $(pwd)"
echo "✅ nas-http-server.py - Ready for deployment"
echo "✅ Web interface already running on port 8080"
echo ""

echo "📋 STEP 2: Access the NAS"
echo "=========================="
echo "Option A - Direct SSH access:"
echo "  ssh admin@10.1.21.3"
echo ""
echo "Option B - Use Synology DSM Web Interface:"
echo "  1. Open browser: http://10.1.21.3:5000"
echo "  2. Login with admin credentials"
echo "  3. Open File Station"
echo "  4. Navigate to BCP-Folder-PHI-Test"
echo ""

echo "📋 STEP 3: Upload Server File"
echo "=============================="
echo "Copy nas-http-server.py to NAS at:"
echo "  /volume1/BCP-Folder-PHI-Test/nas-http-server.py"
echo ""

echo "📋 STEP 4: Stop Current Server"
echo "==============================="
echo "On the NAS, run:"
echo "  pkill -f 'python.*http.server'"
echo "  # This stops the basic HTTP server on port 8080"
echo ""

echo "📋 STEP 5: Start New Server"
echo "============================"
echo "On the NAS, run:"
echo "  cd /volume1/BCP-Folder-PHI-Test"
echo "  nohup python3 nas-http-server.py > server.log 2>&1 &"
echo "  echo \"Server started with PID: \$!\""
echo ""

echo "📋 STEP 6: Test Deployment"
echo "==========================="
echo "From your Mac, test these URLs:"
echo "  curl http://10.1.21.3:5000/health"
echo "  curl http://10.1.21.3:8080/        # Web interface"
echo ""

echo "📋 STEP 7: Configure Web Interface"
echo "==================================="
echo "The web interface at http://10.1.21.3:8080 will now connect to:"
echo "  API endpoint: http://10.1.21.3:5000"
echo "  Health check: http://10.1.21.3:5000/bcp-api/health"
echo "  Patient search: http://10.1.21.3:5000/bcp-api/search"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "=================="
echo "If the server doesn't start:"
echo "  1. Check logs: tail -f /volume1/BCP-Folder-PHI-Test/server.log"
echo "  2. Check Python: python3 --version"
echo "  3. Check CSV file: ls -la /volume1/BCP-Folder-PHI-Test/offline_patient_chart_redacted.csv"
echo ""

echo "🔄 QUICK TEST COMMANDS"
echo "======================"
echo "# Test server status:"
echo "curl -s http://10.1.21.3:5000/health | jq ."
echo ""
echo "# Test patient search:"
echo "curl -X POST http://10.1.21.3:5000/bcp-api/search \\"
echo "  -H 'Content-Type: application/json' \\"
echo "  -d '{\"patientId\": \"test123\"}'"
echo ""

echo "📱 WEB INTERFACE ACCESS"
echo "======================="
echo "Once deployed, access the full system at:"
echo "  🌐 Web Interface: http://10.1.21.3:8080/"
echo "  🔧 API Server: http://10.1.21.3:5000/"
echo ""
echo "🔒 PHI COMPLIANCE: All patient data remains on NAS - no local storage"
echo ""

# Also copy the current file for easy transfer
echo "📦 Copying nas-http-server.py to Desktop for easy transfer..."
cp nas-http-server.py ~/Desktop/nas-http-server.py 2>/dev/null && echo "✅ File copied to ~/Desktop/nas-http-server.py" || echo "⚠️ Could not copy to Desktop"

echo ""
echo "🎯 NEXT STEPS:"
echo "1. Follow the manual deployment steps above"
echo "2. Test the API endpoints"
echo "3. Verify the web interface can search patients"
echo "4. Commit your progress to git"